import SigninButtons from '@/components/SigninButtons'
import React from 'react'
import { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { authoptions } from '../api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation'
export const metadata: Metadata = {
    title: 'Sign In',
    description: 'Generated by create next app',
}
const Signin = async () => {
    const session = await getServerSession(authoptions);
    if (session) {
        redirect("/dashboard")
    }
    return (
        <div>
            <SigninButtons />
        </div>
    )
}

export default Signin
