//@ts-nocheck
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AuthProvider from '@/Providers/AuthProvider'
import ModeProvider from '@/Providers/ModeProvider'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ModeProvider>
            <div className="box">
              <Navbar />
              <div className="my-14">
                {children}
              </div>
              <Footer />
            </div>
            <Toaster />
          </ModeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
