// import Post from '@/components/Post'
// import { postData } from '@/data'
import Link from 'next/link'
import React from 'react'
import { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { authoptions } from '../api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation'
import Profile from '@/components/Profile'
import { Tpost } from '@/app/types'
import Post from '../post/page'
export const metadata: Metadata = {
    title: 'My Posts',
    description: 'Generated by create next app',
}

const getPosts = async (email: string) => {
    try {
        const res = await fetch(`${process.env.NEXTAUTH_URL}/api/author/${email}`, { cache: "no-store" })
        if (res.ok) {
            const { posts } = await res.json()
            return posts;
        }

    } catch (err) {
        console.log("Error => ", err)
        return null;

    }
}
const Dashboard = async () => {
    const session = await getServerSession(authoptions);
    const email = session?.user?.email;
    let posts = []
    if (!session) {
        redirect("/signin")
    }

    if (email) {
        posts = await getPosts(email);

    }
    return (
        <div className=' min-h-[69vh]'>
            <Profile />
            <h1 className='text-4xl font-bold text-black dark:text-gray-200 my-5'>My Posts</h1>
            {posts && posts.length > 0 ? (
                posts && posts.map((post: Tpost) => (
                    <Post key={post.id} id={post.id} author={"You"} authorEmail={post.authorEmail} date={post.createdAt} thumbnail={post.imageUrl} category={post.catName} title={post.title}
                        desc={post.desc} content={post.content} links={post.links || []} />
                ))
            )
                : (
                    <p className=" flex items-start   gap-2 font-medium text-lg text-gray-500">No Posts Available currently.
                        <Link href={`/createpost`} aria-label='Create Post' className=' underline font-semibold text-gray-700'>Create Post</Link></p>
                )
            }
        </div>
    )
}

export default Dashboard
